# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proc_staffInfo_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtChart import *

from DataViewWidgets.piechart_widget.pieChartMain import PieChartFrame
from DataViewWidgets.linechart_widget.lineChartMain import LineChartFrame


class Ui_Proc_StaffInfo(object):
    def setupUi(self, Proc_StaffInfo):
        Proc_StaffInfo.setObjectName("Proc_StaffInfo")
        Proc_StaffInfo.resize(1126, 788)
        self.layout_main = QtWidgets.QGridLayout(Proc_StaffInfo)
        self.layout_main.setObjectName("layout_main")

        '''left part'''
        self.layout_leftshow = QtWidgets.QVBoxLayout()
        self.layout_leftshow.setObjectName("layout_leftshow")
        self.widget_stafftable_container = QtWidgets.QWidget(Proc_StaffInfo)
        self.widget_stafftable_container.setObjectName("widget_stafftable_container")
        self.layout_widgetStaffTableContainer = QtWidgets.QGridLayout(self.widget_stafftable_container)
        self.layout_widgetStaffTableContainer.setObjectName("layout_widgetStaffTableContainer")
        self.tableView = QtWidgets.QTableView(self.widget_stafftable_container)
        self.tableView.setObjectName("tableView")
        self.layout_widgetStaffTableContainer.addWidget(self.tableView, 1, 0, 1, 1)
        self.label_staffTableTitle = QtWidgets.QLabel(self.widget_stafftable_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_staffTableTitle.setFont(font)
        self.label_staffTableTitle.setObjectName("label_staffTableTitle")
        self.layout_widgetStaffTableContainer.addWidget(self.label_staffTableTitle, 0, 0, 1, 1)
        self.layout_leftshow.addWidget(self.widget_stafftable_container)
        self.widget_totalData_container = QtWidgets.QWidget(Proc_StaffInfo)
        self.widget_totalData_container.setObjectName("widget_totalData_container")
        self.layout_widgetTotalInfoContainer = QtWidgets.QGridLayout(self.widget_totalData_container)
        self.layout_widgetTotalInfoContainer.setObjectName("layout_widgetTotalInfoContainer")

        ''' @widget_totalHistoryChart: widget to show total data chart'''
        # self.widget_totalHistoryChart = QtWidgets.QWidget(self.widget_totalData_container)
        self.widget_totalHistoryChart = LineChartFrame([1,2,1,2,1,2,1],"公司过去一周考勤率","",["周一","周二","周三","周四","周五","周六","周日"])
        self.widget_totalHistoryChart.setObjectName("widget_totalHistoryChart")
        # set translicent
        #self.widget_totalHistoryChart.setAttribute(Qt.WA_TranslucentBackground, True)
        self.widget_totalHistoryChart.setStyleSheet("""QWidget{background-color: rgba(255,255,255,0);}""")

        self.layout_widgetTotalInfoContainer.addWidget(self.widget_totalHistoryChart, 0, 0, 1, 1)

        self.widget_totalData = QtWidgets.QWidget(self.widget_totalData_container)
        self.widget_totalData.setObjectName("widget_totalData")
        self.layout_widgetTotalInfoContainer.addWidget(self.widget_totalData, 0, 1, 1, 1)
        self.layout_widgetTotalInfoContainer.setColumnStretch(0, 3)
        self.layout_widgetTotalInfoContainer.setColumnStretch(1, 2)
        self.layout_leftshow.addWidget(self.widget_totalData_container)
        self.layout_leftshow.setStretch(0, 4)
        self.layout_leftshow.setStretch(1, 2)
        self.layout_main.addLayout(self.layout_leftshow, 0, 0, 1, 1)

        '''right part'''
        self.layout_right = QtWidgets.QVBoxLayout()
        self.layout_right.setObjectName("layout_right")
        self.layout_searchshow = QtWidgets.QHBoxLayout()
        self.layout_searchshow.setObjectName("layout_searchshow")
        self.lineEditSearch = QtWidgets.QLineEdit(Proc_StaffInfo)
        self.lineEditSearch.setObjectName("lineEditSearch")
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setWeight(75)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setPlaceholderText("请输入工号")
        self.layout_searchshow.addWidget(self.lineEditSearch)
        self.btn_search = QtWidgets.QPushButton(Proc_StaffInfo)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setObjectName("btn_search")
        self.layout_searchshow.addWidget(self.btn_search)
        self.layout_right.addLayout(self.layout_searchshow)
        self.widget_staffData_container = QtWidgets.QWidget(Proc_StaffInfo)
        self.widget_staffData_container.setObjectName("widget_staffData_container")
        self.layout_widgetStaffDataContainer = QtWidgets.QGridLayout(self.widget_staffData_container)
        self.layout_widgetStaffDataContainer.setObjectName("layout_widgetStaffDataContainer")
        self.widget_showStaffHistoryChart = LineChartFrame([1,2,1,2,1,2,1],"员工过去一周考勤率","",["周一","周二","周三","周四","周五","周六","周日"])
        self.widget_showStaffHistoryChart.setObjectName("widget_showStaffHistoryChart")

        self.widget_showStaffHistoryChart.setAttribute(Qt.WA_TranslucentBackground, True)
        self.widget_showStaffHistoryChart.setStyleSheet("""QWidget{background-color: rgba(255,255,255,0)}""")

        self.layout_widgetStaffDataContainer.addWidget(self.widget_showStaffHistoryChart, 0, 0, 1, 1)
        self.widget_showStaffDataNum = QtWidgets.QWidget(self.widget_staffData_container)
        self.widget_showStaffDataNum.setObjectName("widget_showStaffDataNum")
        self.layout_widgetStaffDataContainer.addWidget(self.widget_showStaffDataNum, 1, 0, 1, 1)
        self.layout_right.addWidget(self.widget_staffData_container)
        self.widget_opbtn_container = QtWidgets.QWidget(Proc_StaffInfo)
        self.widget_opbtn_container.setObjectName("widget_opbtn_container")
        self.layout_widgetOpbtnContainer = QtWidgets.QVBoxLayout(self.widget_opbtn_container)
        self.layout_widgetOpbtnContainer.setObjectName("layout_widgetOpbtnContainer")
        self.btn_showStaffAddWin = QtWidgets.QPushButton(self.widget_opbtn_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_showStaffAddWin.setFont(font)
        self.btn_showStaffAddWin.setObjectName("btn_showStaffAddWin")
        self.layout_widgetOpbtnContainer.addWidget(self.btn_showStaffAddWin)
        self.lineEditDeleteID = QtWidgets.QLineEdit(self.widget_opbtn_container)
        self.lineEditDeleteID.setObjectName("lineEditDeleteID")
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setWeight(75)
        self.lineEditDeleteID.setFont(font)
        self.lineEditDeleteID.setPlaceholderText("请输入工号")

        self.layout_widgetOpbtnContainer.addWidget(self.lineEditDeleteID)
        self.layout_btnDelete = QtWidgets.QHBoxLayout()
        self.layout_btnDelete.setObjectName("layout_btnDelete")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_btnDelete.addItem(spacerItem)
        self.pushButtonDelete = QtWidgets.QPushButton(self.widget_opbtn_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.layout_btnDelete.addWidget(self.pushButtonDelete)
        self.layout_widgetOpbtnContainer.addLayout(self.layout_btnDelete)
        self.layout_right.addWidget(self.widget_opbtn_container)

        '''layout setting'''
        self.layout_right.setStretch(0, 1)
        self.layout_right.setStretch(1, 12)
        self.layout_right.setStretch(2, 3)
        self.layout_main.addLayout(self.layout_right, 0, 1, 1, 1)

        self.layout_widgetStaffDataContainer.setRowStretch(0,2)
        self.layout_widgetStaffDataContainer.setRowStretch(1,3)
        self.layout_main.setColumnStretch(0, 7)
        self.layout_main.setColumnStretch(1, 3)
        self.layout_main.setHorizontalSpacing(11)
        self.layout_main.setVerticalSpacing(11)

        '''enhance shadow effects'''
        self.setShadowEffect(self.widget_opbtn_container)
        self.setShadowEffect(self.widget_staffData_container)
        self.setShadowEffect(self.widget_stafftable_container)
        self.setShadowEffect(self.widget_showStaffDataNum)
        self.setShadowEffect(self.widget_totalData)

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_totalData_container.setGraphicsEffect(shadow_effect)
        self.widget_totalData_container.setStyleSheet("""QWidget#widget_totalData_container{
                                background-color: rgba(255,255,255,180);
                                border-radius: 8px}""")

        self.widget_stafftable_container.setStyleSheet("""QWidget#widget_stafftable_container{
                                background-color: rgba(255,255,255,180);
                                border-radius: 8px}""")
        self.widget_staffData_container.setStyleSheet("""QWidget#widget_staffData_container{
                                background-color: rgba(175,238,238,180);
                                border-radius: 8px}""")
        self.widget_totalData.setStyleSheet("""QWidget#widget_totalData{
                                background-color: rgba(255,255,255,90);
                                border-radius: 8px}""")
        self.widget_showStaffDataNum.setStyleSheet("""QWidget#widget_showStaffDataNum{
                                background-color: rgba(255,255,255,90);
                                border-radius: 8px}""")

        '''set line edit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.lineEditDeleteID.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEditSearch.setStyleSheet(LEditStyle.read())
            # LEditStyle.seek(0)

        self.lineEditSearch.setValidator(QIntValidator(100,1000))
        self.lineEditDeleteID.setValidator(QIntValidator(100,1000))

        '''set btn style'''
        with open("Qss/push_button_style.qss") as BtnStyle:
            self.btn_search.setStyleSheet(BtnStyle.read())
            BtnStyle.seek(0)
            self.btn_showStaffAddWin.setStyleSheet(BtnStyle.read())

        with open("Qss/push_button_style_lightred.qss") as BtnStyle:
            self.pushButtonDelete.setStyleSheet(BtnStyle.read())
        
        '''set data charts'''



        self.retranslateUi(Proc_StaffInfo)
        QtCore.QMetaObject.connectSlotsByName(Proc_StaffInfo)

    def retranslateUi(self, Proc_StaffInfo):
        _translate = QtCore.QCoreApplication.translate
        Proc_StaffInfo.setWindowTitle(_translate("Proc_StaffInfo", "Form"))
        self.label_staffTableTitle.setText(_translate("Proc_StaffInfo", "员工考勤数据:"))
        self.btn_search.setText(_translate("Proc_StaffInfo", "搜索"))
        self.btn_showStaffAddWin.setText(_translate("Proc_StaffInfo", "添加员工"))
        self.pushButtonDelete.setText(_translate("Proc_StaffInfo", "删除员工"))

    def setShadowEffect(self, widget):
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        widget.setGraphicsEffect(shadow_effect)


if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    TestUi.main_ui=Ui_Proc_StaffInfo()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )