# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requests_verify_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import pymysql
import socket
import time
import json
from client import breakget,complainget,breakdayapply,complainapply
global index
index=int(0)
host=socket.gethostname()
port=9999
global model
model=QStandardItemModel(16,5)
global result
global breakresult
global breakmodel
class Ui_Requests_Verify(object):
    def setupUi(self, Requests_Verify_ui):
        Requests_Verify_ui.setObjectName("Requests_Verify_ui")
        Requests_Verify_ui.resize(1048, 701)

        '''main layout'''
        self.gridLayout_4 = QtWidgets.QGridLayout(Requests_Verify_ui)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setVerticalSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")


        self.widget_breakday_container = QtWidgets.QWidget(Requests_Verify_ui)
        self.widget_breakday_container.setObjectName("widget_breakday_container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_breakday_container)
        self.gridLayout_2.setHorizontalSpacing(11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_breakday_show = QtWidgets.QVBoxLayout()
        self.layout_breakday_show.setObjectName("layout_breakday_show")
        self.label_breakday_title = QtWidgets.QLabel(self.widget_breakday_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_breakday_title.setFont(font)
        self.label_breakday_title.setObjectName("label_breakday_title")
        self.layout_breakday_show.addWidget(self.label_breakday_title)
        self.tableView_breakday_show = QtWidgets.QTableView(self.widget_breakday_container)
        self.tableView_breakday_show.setObjectName("tableView_breakday_show")
        self.layout_breakday_show.addWidget(self.tableView_breakday_show)
        self.gridLayout_2.addLayout(self.layout_breakday_show, 0, 0, 1, 1)
        self.widget_breakday_deal = QtWidgets.QWidget(self.widget_breakday_container)
        self.widget_breakday_deal.setObjectName("widget_breakday_deal")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_breakday_deal)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layout_showBasicInfo = QtWidgets.QHBoxLayout()
        self.layout_showBasicInfo.setObjectName("layout_showBasicInfo")
        self.label_showId = QtWidgets.QLabel(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showId.setFont(font)
        self.label_showId.setObjectName("label_showId")
        self.layout_showBasicInfo.addWidget(self.label_showId)
        self.LEdit_showId = QtWidgets.QLineEdit(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Microsoft YaHei")
        self.LEdit_showId.setFont(font)
        self.LEdit_showId.setObjectName("LEdit_showId")
        self.layout_showBasicInfo.addWidget(self.LEdit_showId)
        self.label_showName = QtWidgets.QLabel(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showName.setFont(font)
        self.label_showName.setObjectName("label_showName")
        self.layout_showBasicInfo.addWidget(self.label_showName)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Microsoft YaHei")
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.layout_showBasicInfo.addWidget(self.lineEdit)
        self.gridLayout_3.addLayout(self.layout_showBasicInfo, 0, 0, 1, 1)
        self.layout_showBreakRsn = QtWidgets.QVBoxLayout()
        self.layout_showBreakRsn.setObjectName("layout_showBreakRsn")
        self.label = QtWidgets.QLabel(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layout_showBreakRsn.addWidget(self.label)
        self.tedit_showBreakRsn = QtWidgets.QTextEdit(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Microsoft YaHei")
        self.tedit_showBreakRsn.setFont(font)
        self.tedit_showBreakRsn.setObjectName("tedit_showBreakRsn")
        self.layout_showBreakRsn.addWidget(self.tedit_showBreakRsn)
        self.gridLayout_3.addLayout(self.layout_showBreakRsn, 2, 0, 1, 1)
        self.layout_showBreakTime = QtWidgets.QHBoxLayout()
        self.layout_showBreakTime.setObjectName("layout_showBreakTime")
        self.label_showBreakTime = QtWidgets.QLabel(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showBreakTime.setFont(font)
        self.label_showBreakTime.setObjectName("label_showBreakTime")
        self.layout_showBreakTime.addWidget(self.label_showBreakTime)
        self.LEdit_showBreakTime = QtWidgets.QLineEdit(self.widget_breakday_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.LEdit_showBreakTime.setFont(font)
        self.LEdit_showBreakTime.setObjectName("LEdit_showBreakTime")
        self.layout_showBreakTime.addWidget(self.LEdit_showBreakTime)
        self.gridLayout_3.addLayout(self.layout_showBreakTime, 1, 0, 1, 1)
        self.layout_showBreakBtn = QtWidgets.QHBoxLayout()
        self.layout_showBreakBtn.setObjectName("layout_showBreakBtn")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_showBreakBtn.addItem(spacerItem)
        self.btn_breakPass = QtWidgets.QPushButton(self.widget_breakday_deal)
        self.btn_breakPass.setObjectName("btn_breakPass")
        self.layout_showBreakBtn.addWidget(self.btn_breakPass)
        self.btn_breakDeny = QtWidgets.QPushButton(self.widget_breakday_deal)
        self.btn_breakDeny.setObjectName("btn_breakDeny")
        self.layout_showBreakBtn.addWidget(self.btn_breakDeny)
        self.gridLayout_3.addLayout(self.layout_showBreakBtn, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_breakday_deal, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_breakday_container, 0, 0, 1, 1)
        self.widget_complain_container = QtWidgets.QWidget(Requests_Verify_ui)
        self.widget_complain_container.setObjectName("widget_complain_container")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_complain_container)
        self.gridLayout.setHorizontalSpacing(11)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_complain_show = QtWidgets.QVBoxLayout()
        self.layout_complain_show.setObjectName("layout_complain_show")
        self.label_complain_title = QtWidgets.QLabel(self.widget_complain_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_complain_title.setFont(font)
        self.label_complain_title.setObjectName("label_complain_title")
        self.layout_complain_show.addWidget(self.label_complain_title)
        self.tableView_complain_show = QtWidgets.QTableView(self.widget_complain_container)
        self.tableView_complain_show.setObjectName("tableView_complain_show")
        self.layout_complain_show.addWidget(self.tableView_complain_show)
        self.gridLayout.addLayout(self.layout_complain_show, 0, 0, 1, 1)
        self.widget_complain_deal = QtWidgets.QWidget(self.widget_complain_container)
        self.widget_complain_deal.setObjectName("widget_complain_deal")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_complain_deal)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.layout_showComplainTime = QtWidgets.QHBoxLayout()
        self.layout_showComplainTime.setObjectName("layout_showComplainTime")
        self.label_showComplainTime = QtWidgets.QLabel(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showComplainTime.setFont(font)
        self.label_showComplainTime.setObjectName("label_showComplainTime")
        self.layout_showComplainTime.addWidget(self.label_showComplainTime)
        self.LEdit_showComplainTime = QtWidgets.QLineEdit(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Microsoft YaHei")
        self.LEdit_showComplainTime.setFont(font)
        self.LEdit_showComplainTime.setObjectName("LEdit_showComplainTime")
        self.layout_showComplainTime.addWidget(self.LEdit_showComplainTime)
        self.gridLayout_5.addLayout(self.layout_showComplainTime, 1, 0, 1, 1)
        self.layout_showBasicInfo_cmpn = QtWidgets.QHBoxLayout()
        self.layout_showBasicInfo_cmpn.setObjectName("layout_showBasicInfo_cmpn")
        self.label_showId_cmpn = QtWidgets.QLabel(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showId_cmpn.setFont(font)
        self.label_showId_cmpn.setObjectName("label_showId_cmpn")
        self.layout_showBasicInfo_cmpn.addWidget(self.label_showId_cmpn)
        self.LEdit_showId_cmpn = QtWidgets.QLineEdit(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Microsoft YaHei")
        self.LEdit_showId_cmpn.setFont(font)
        self.LEdit_showId_cmpn.setObjectName("LEdit_showId_cmpn")
        self.layout_showBasicInfo_cmpn.addWidget(self.LEdit_showId_cmpn)
        self.label_showName_cmpn = QtWidgets.QLabel(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showName_cmpn.setFont(font)
        self.label_showName_cmpn.setObjectName("label_showName_cmpn")
        self.layout_showBasicInfo_cmpn.addWidget(self.label_showName_cmpn)
        self.lineEdit_cmpn = QtWidgets.QLineEdit(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.lineEdit_cmpn.setFont(font)
        self.lineEdit_cmpn.setObjectName("lineEdit_cmpn")
        self.layout_showBasicInfo_cmpn.addWidget(self.lineEdit_cmpn)
        self.gridLayout_5.addLayout(self.layout_showBasicInfo_cmpn, 0, 0, 1, 1)
        self.layout_showComplainRsn = QtWidgets.QVBoxLayout()
        self.layout_showComplainRsn.setObjectName("layout_showComplainRsn")
        self.label_showConplainRsn = QtWidgets.QLabel(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_showConplainRsn.setFont(font)
        self.label_showConplainRsn.setObjectName("label_showConplainRsn")
        self.layout_showComplainRsn.addWidget(self.label_showConplainRsn)
        self.tedit_showComplainRsn = QtWidgets.QTextEdit(self.widget_complain_deal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Microsoft YaHei")
        self.tedit_showComplainRsn.setFont(font)
        self.tedit_showComplainRsn.setObjectName("tedit_showComplainRsn")
        self.layout_showComplainRsn.addWidget(self.tedit_showComplainRsn)
        self.layout_showComplainBtn = QtWidgets.QHBoxLayout()
        self.layout_showComplainBtn.setObjectName("layout_showComplainBtn")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_showComplainBtn.addItem(spacerItem1)
        self.btn_complainPass = QtWidgets.QPushButton(self.widget_complain_deal)
        self.btn_complainPass.setObjectName("btn_complainPass")
        self.layout_showComplainBtn.addWidget(self.btn_complainPass)
        self.btn_complainDeny = QtWidgets.QPushButton(self.widget_complain_deal)
        self.btn_complainDeny.setObjectName("btn_complainDeny")
        self.layout_showComplainBtn.addWidget(self.btn_complainDeny)
        self.layout_showComplainRsn.addLayout(self.layout_showComplainBtn)

        '''layout settings'''
        self.gridLayout_5.addLayout(self.layout_showComplainRsn, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_complain_deal, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_complain_container, 1, 0, 1, 1)

        '''enhance shadow effects'''
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_breakday_container.setGraphicsEffect(shadow_effect)
        self.widget_breakday_container.setStyleSheet("""QWidget#widget_breakday_container{
                                                    background-color: rgba(255,255,255,135);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_breakday_deal.setGraphicsEffect(shadow_effect)
        self.widget_breakday_deal.setStyleSheet("""QWidget#widget_breakday_deal{
                                                    background-color: rgba(255,255,255,145);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_complain_container.setGraphicsEffect(shadow_effect)
        self.widget_complain_container.setStyleSheet("""QWidget#widget_complain_container{
                                                    background-color: rgba(255,255,255,135);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_complain_deal.setGraphicsEffect(shadow_effect)
        self.widget_complain_deal.setStyleSheet("""QWidget#widget_complain_deal{
                                                    background-color: rgba(255,255,255,145);
                                                    border-radius: 8px}""")

        '''set line edit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.LEdit_showBreakTime.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_showComplainTime.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_showId.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_showId_cmpn.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEdit.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEdit_cmpn.setStyleSheet(LEditStyle.read())
            #LEditStyle.seek(0)

        



        '''set btn style'''
        with open("Qss/push_button_style.qss") as BtnStyle:
            self.btn_breakPass.setStyleSheet(BtnStyle.read())
            BtnStyle.seek(0)
            self.btn_complainPass.setStyleSheet(BtnStyle.read())
            #BtnStyle.seek(0)
        
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_breakPass.setFont(font)
        self.btn_complainPass.setFont(font)

        with open("Qss/push_button_style_lightred.qss") as BtnStyle:
            self.btn_breakDeny.setStyleSheet(BtnStyle.read())
            BtnStyle.seek(0)
            self.btn_complainDeny.setStyleSheet(BtnStyle.read())
            #BtnStyle.seek(0)

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_breakDeny.setFont(font)
        self.btn_complainDeny.setFont(font)

        '''set text edit style'''
        with open("Qss/textedit_style.qss") as TEditStyle:
            self.tedit_showBreakRsn.setStyleSheet(TEditStyle.read())
            TEditStyle.seek(0)
            self.tedit_showComplainRsn.setStyleSheet(TEditStyle.read())
            TEditStyle.seek(0)

        '''set table style'''
        with open("Qss/flatwhite_style.qss") as TableStyle:
            self.tableView_breakday_show.setStyleSheet(TableStyle.read())
            TableStyle.seek(0)
            self.tableView_complain_show.setStyleSheet(TableStyle.read())

        self.retranslateUi(Requests_Verify_ui)
        QtCore.QMetaObject.connectSlotsByName(Requests_Verify_ui)

        self.btn_breakPass.clicked.connect(Requests_Verify_ui.breakpass)
        self.btn_breakDeny.clicked.connect(Requests_Verify_ui.breakdeny)
        self.btn_complainPass.clicked.connect(Requests_Verify_ui.complainpass)
        self.btn_complainDeny.clicked.connect(Requests_Verify_ui.complaindeny)
        
        self.btn_breakPass.clicked.connect(self.breakpass)
        self.btn_breakDeny.clicked.connect(self.breakdeny)
#        self.btn_complainPass.clicked.connect(self.complainpass)
#        self.btn_complainDeny.clicked.connect(self.complaindeny)
        self.tableView_breakday_show.clicked.connect(self.cli)
        self.tableView_complain_show.clicked.connect(self.complaincli)


        
        global result
        result=complainget()
        
        #print(result)
        global i
        i=0
        for record in result:
            i=i+1
        global model
        model=QStandardItemModel(i,5)#存储任意结构数据
        model.setHorizontalHeaderLabels(['姓名','申诉原因',])
        #水平方向标签拓展剩下的窗口部分，填满表格
        self.tableView_complain_show.horizontalHeader().setStretchLastSection(True)
        #水平方向，表格大小拓展到适当的尺寸   
        self.tableView_complain_show.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)






        for row in range(i):
            for column in range(5):
                i=QStandardItem(result[row][column])
                #print(i)
                model.setItem(row,column,i)
        self.tableView_complain_show.setModel(model)


        print("!!!!!!")
        global breakresult
        global breakmodel
        
        breakresult=breakget()
        #print(breakresult)
        i=0
        for record in breakresult:
            i=i+1
        breakmodel=QStandardItemModel(i,6)#存储任意结构数据
        breakmodel.setHorizontalHeaderLabels(['工号','姓名','请假原因','开始时间','截止时间','审核状态'])
        #水平方向标签拓展剩下的窗口部分，填满表格
        self.tableView_breakday_show.horizontalHeader().setStretchLastSection(True)
        #水平方向，表格大小拓展到适当的尺寸
        self.tableView_breakday_show.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        print("!")
        for row in range(i):
            for column in range(6):
                i=QStandardItem(breakresult[row][column])
                #print(i)
                breakmodel.setItem(row,column,i)
        self.tableView_breakday_show.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableView_breakday_show.setModel(breakmodel)




    def cli(self, qModelIndex):
        global index
        index=qModelIndex.row()
        self.LEdit_showId.setText(breakresult[qModelIndex.row()][0])
        self.lineEdit.setText(breakresult[qModelIndex.row()][1])
        bt=breakresult[qModelIndex.row()][3]+"至"+breakresult[qModelIndex.row()][4]
        self.LEdit_showBreakTime.setText(bt)
        self.tedit_showBreakRsn.setText(breakresult[qModelIndex.row()][2])
        #print(qModelIndex.row())

    def complaincli(self, qModelIndex):
        global result
        self.LEdit_showId_cmpn.setText(result[qModelIndex.row()][0])
        self.lineEdit_cmpn.setText(result[qModelIndex.row()][1])
        self.LEdit_showComplainTime.setText(result[qModelIndex.row()][2])
        self.tedit_showComplainRsn.setText(result[qModelIndex.row()][4])
        
        #print(qModelIndex.row())


    def breakpass(self):
        global index
        i=QStandardItem("通过")
        breakmodel.setItem(index,5,i)
        self.tableView_breakday_show.setModel(breakmodel)
    def breakdeny(self):
        i=QStandardItem("驳回")
        breakmodel.setItem(index,5,i)
        self.tableView_breakday_show.setModel(breakmodel)
    def retranslateUi(self, Requests_Verify_ui):
        _translate = QtCore.QCoreApplication.translate
        Requests_Verify_ui.setWindowTitle(_translate("Requests_Verify_ui", "Form"))
        self.label_breakday_title.setText(_translate("Requests_Verify_ui", "请假申请："))
        self.label_showId.setText(_translate("Requests_Verify_ui", "工号"))
        self.label_showName.setText(_translate("Requests_Verify_ui", "姓名"))
        self.label.setText(_translate("Requests_Verify_ui", "请假理由："))
        self.label_showBreakTime.setText(_translate("Requests_Verify_ui", "请假时段："))
        self.btn_breakPass.setText(_translate("Requests_Verify_ui", "通过"))
        self.btn_breakDeny.setText(_translate("Requests_Verify_ui", "驳回"))
        self.label_complain_title.setText(_translate("Requests_Verify_ui", "考勤申诉："))
        self.label_showComplainTime.setText(_translate("Requests_Verify_ui", "申诉时间及原因："))
        self.label_showId_cmpn.setText(_translate("Requests_Verify_ui", "工号"))
        self.label_showName_cmpn.setText(_translate("Requests_Verify_ui", "姓名"))
        self.label_showConplainRsn.setText(_translate("Requests_Verify_ui", "请假理由："))
        self.btn_complainPass.setText(_translate("Requests_Verify_ui", "通过"))
        self.btn_complainDeny.setText(_translate("Requests_Verify_ui", "驳回"))


if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    #TestUi.setWindowFlags (Qt.FramelessWindowHint)
    TestUi.main_ui=Ui_Requests_Verify()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )
