# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proc_mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtChart import *

from DataViewWidgets.barChart.barchartMain import BarchartFrame
from DataViewWidgets.piechart_widget.pieChartMain import PieChartFrame
from DataViewWidgets.linechart_widget.lineChartMain import LineChartFrame
from PyUiWidgets.uni_showdateinfo_widget import Uni_ShowDateInfo_Widget

class Ui_Proc_MainPage(object):
    def setupUi(self, Proc_MainPage):
        Proc_MainPage.setObjectName("Proc_MainPage")
        Proc_MainPage.resize(1052, 749)

        '''main layout'''
        self.verticalLayout = QtWidgets.QVBoxLayout(Proc_MainPage)
        self.verticalLayout.setSpacing(13)
        self.verticalLayout.setObjectName("verticalLayout")
        
        
        '''top part'''
        self.widget_topBar_container = QtWidgets.QWidget(Proc_MainPage)
        self.widget_topBar_container.setObjectName("widget_topBar_container")
        self.layout_topBar_main = QtWidgets.QHBoxLayout(self.widget_topBar_container)
        self.layout_topBar_main.setSpacing(20)
        self.layout_topBar_main.setObjectName("layout_topBar_main")
        self.widget_topBar_totalNum = QtWidgets.QWidget(self.widget_topBar_container)
        self.widget_topBar_totalNum.setObjectName("widget_topBar_totalNum")
        self.layout_topBar_1 = QtWidgets.QVBoxLayout(self.widget_topBar_totalNum)
        self.layout_topBar_1.setObjectName("layout_topBar_1")
        self.label_topBar_totalNum_title = QtWidgets.QLabel(self.widget_topBar_totalNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_totalNum_title.setFont(font)
        self.label_topBar_totalNum_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_totalNum_title.setObjectName("label_topBar_totalNum_title")
        self.layout_topBar_1.addWidget(self.label_topBar_totalNum_title)
        self.line = QtWidgets.QFrame(self.widget_topBar_totalNum)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout_topBar_1.addWidget(self.line)
        self.label_topBar_totalNum_num = QtWidgets.QLabel(self.widget_topBar_totalNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_totalNum_num.setFont(font)
        self.label_topBar_totalNum_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_totalNum_num.setObjectName("label_topBar_totalNum_num")
        self.layout_topBar_1.addWidget(self.label_topBar_totalNum_num)
        self.layout_topBar_main.addWidget(self.widget_topBar_totalNum)
        self.widget_topBar_checkedNum = QtWidgets.QWidget(self.widget_topBar_container)
        self.widget_topBar_checkedNum.setObjectName("widget_topBar_checkedNum")
        self.layout_topBar_2 = QtWidgets.QVBoxLayout(self.widget_topBar_checkedNum)
        self.layout_topBar_2.setObjectName("layout_topBar_2")
        self.label_topBar_checkedNum_title = QtWidgets.QLabel(self.widget_topBar_checkedNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_checkedNum_title.setFont(font)
        self.label_topBar_checkedNum_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_checkedNum_title.setObjectName("label_topBar_checkedNum_title")
        self.layout_topBar_2.addWidget(self.label_topBar_checkedNum_title)
        self.line_2 = QtWidgets.QFrame(self.widget_topBar_checkedNum)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layout_topBar_2.addWidget(self.line_2)
        self.label_topBar_checkedNum_num = QtWidgets.QLabel(self.widget_topBar_checkedNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_checkedNum_num.setFont(font)
        self.label_topBar_checkedNum_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_checkedNum_num.setObjectName("label_topBar_checkedNum_num")
        self.layout_topBar_2.addWidget(self.label_topBar_checkedNum_num)
        self.layout_topBar_main.addWidget(self.widget_topBar_checkedNum)
        self.widget_topBar_requestNum = QtWidgets.QWidget(self.widget_topBar_container)
        self.widget_topBar_requestNum.setObjectName("widget_topBar_requestNum")
        self.layout_topBar_3 = QtWidgets.QVBoxLayout(self.widget_topBar_requestNum)
        self.layout_topBar_3.setObjectName("layout_topBar_3")
        self.label_topBar_requestNum_title = QtWidgets.QLabel(self.widget_topBar_requestNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_requestNum_title.setFont(font)
        self.label_topBar_requestNum_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_requestNum_title.setObjectName("label_topBar_requestNum_title")
        self.layout_topBar_3.addWidget(self.label_topBar_requestNum_title)
        self.line_3 = QtWidgets.QFrame(self.widget_topBar_requestNum)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layout_topBar_3.addWidget(self.line_3)
        self.label_topBar_requestNum_num = QtWidgets.QLabel(self.widget_topBar_requestNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setPointSize(12)
        self.label_topBar_requestNum_num.setFont(font)
        self.label_topBar_requestNum_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_requestNum_num.setObjectName("label_topBar_requestNum_num")
        self.layout_topBar_3.addWidget(self.label_topBar_requestNum_num)
        self.layout_topBar_main.addWidget(self.widget_topBar_requestNum)
        self.widget_topBar_personChgNum = QtWidgets.QWidget(self.widget_topBar_container)
        self.widget_topBar_personChgNum.setObjectName("widget_topBar_personChgNum")
        self.layout_topBar_4 = QtWidgets.QVBoxLayout(self.widget_topBar_personChgNum)
        self.layout_topBar_4.setObjectName("layout_topBar_4")
        self.label_topBar_personChgNum_title = QtWidgets.QLabel(self.widget_topBar_personChgNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_personChgNum_title.setFont(font)
        self.label_topBar_personChgNum_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_personChgNum_title.setObjectName("label_topBar_personChgNum_title")
        self.layout_topBar_4.addWidget(self.label_topBar_personChgNum_title)
        self.line_4 = QtWidgets.QFrame(self.widget_topBar_personChgNum)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layout_topBar_4.addWidget(self.line_4)
        self.label_topBar_personChgNum_num = QtWidgets.QLabel(self.widget_topBar_personChgNum)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_topBar_personChgNum_num.setFont(font)
        self.label_topBar_personChgNum_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topBar_personChgNum_num.setObjectName("label_topBar_personChgNum_num")
        self.layout_topBar_4.addWidget(self.label_topBar_personChgNum_num)
        self.layout_topBar_main.addWidget(self.widget_topBar_personChgNum)
        self.verticalLayout.addWidget(self.widget_topBar_container)


        '''bottom part'''
        self.layout_bottom = QtWidgets.QHBoxLayout()
        self.layout_bottom.setSpacing(15)
        self.layout_bottom.setObjectName("layout_bottom")
        self.layout_chartMain = QtWidgets.QVBoxLayout()
        self.layout_chartMain.setSpacing(15)
        self.layout_chartMain.setObjectName("layout_chartMain")


        '''chart part'''
        '''pie chart part'''
        self.widget_pieChart_container = QtWidgets.QWidget(Proc_MainPage)
        self.widget_pieChart_container.setObjectName("widget_pieChart_container")
        self.layout_widgetPieChartContainer = QtWidgets.QHBoxLayout(self.widget_pieChart_container)
        self.layout_widgetPieChartContainer.setObjectName("layout_widgetPieChartContainer")

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        '''attendance rate pie chart'''
        self.widget_showPieChart_aRate = PieChartFrame([96,3],["考勤率",""])
        self.widget_showPieChart_aRate.setObjectName("widget_showPieChart_aRate")

        self.widget_showPieChart_aRate.ui.chartView.chart().setTitle("本周考勤率")
        self.widget_showPieChart_aRate.ui.chartView.chart().setTitleFont(font)
        series=self.widget_showPieChart_aRate.ui.chartView.chart().series()[0]
        series.slices()[0].setColor(QColor(127,255,0))
        series.slices()[1].setColor(QColor(85,107,47))
        series.slices()[1].setLabelVisible(False)
        self.widget_showPieChart_aRate.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.layout_widgetPieChartContainer.addWidget(self.widget_showPieChart_aRate)
        '''get break day rate pie chart'''
        self.widget_showPieChart_bRate = PieChartFrame([4,99],["请假率",""])
        self.widget_showPieChart_bRate.setObjectName("widget_showPieChart_bRate")

        self.widget_showPieChart_bRate.ui.chartView.chart().setTitle("本周请假率")
        self.widget_showPieChart_bRate.ui.chartView.chart().setTitleFont(font)
        series=self.widget_showPieChart_bRate.ui.chartView.chart().series()[0]
        series.slices()[0].setColor(QColor(255,69,0))
        series.slices()[1].setColor(QColor(188,143,143))
        series.slices()[1].setLabelVisible(False)
        self.widget_showPieChart_bRate.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.layout_widgetPieChartContainer.addWidget(self.widget_showPieChart_bRate)
        self.layout_chartMain.addWidget(self.widget_pieChart_container)

        self.layout_widgetPieChartContainer.setContentsMargins(0,0,0,0)
        self.layout_widgetPieChartContainer.setSpacing(0)

        '''bar chart part'''
        self.widget_barChart_container = QtWidgets.QWidget(Proc_MainPage)
        self.widget_barChart_container.setObjectName("widget_barChart_container")
        self.layout_widgetBarChartContainer = QtWidgets.QHBoxLayout(self.widget_barChart_container)
        self.layout_widgetBarChartContainer.setObjectName("layout_widgetBarChartContainer")
        self.widget_showBarChart = BarchartFrame()
        self.widget_showBarChart.setAttribute(Qt.WA_TranslucentBackground, True)
        self.widget_showBarChart.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.widget_showBarChart.setObjectName("widget_showBarChart")
        self.layout_widgetBarChartContainer.addWidget(self.widget_showBarChart)

        '''show manager info'''
        self.widget_showManagerInfo = QtWidgets.QWidget(self.widget_barChart_container)
        self.widget_showManagerInfo.setObjectName("widget_showManagerInfo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_showManagerInfo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_showManagerName = QtWidgets.QLabel(self.widget_showManagerInfo)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_showManagerName.setFont(font)
        self.label_showManagerName.setObjectName("label_showManagerName")
        self.verticalLayout_2.addWidget(self.label_showManagerName)
        self.LEdit_showManagerName = QtWidgets.QLineEdit(self.widget_showManagerInfo)
        self.LEdit_showManagerName.setObjectName("LEdit_showManagerName")
        self.verticalLayout_2.addWidget(self.LEdit_showManagerName)
        self.label_showManagerId = QtWidgets.QLabel(self.widget_showManagerInfo)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_showManagerId.setFont(font)
        self.label_showManagerId.setObjectName("label_showManagerId")
        self.verticalLayout_2.addWidget(self.label_showManagerId)
        self.LEdit_showManegerId = QtWidgets.QLineEdit(self.widget_showManagerInfo)
        self.LEdit_showManegerId.setObjectName("LEdit_showManegerId")
        self.verticalLayout_2.addWidget(self.LEdit_showManegerId)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.layout_widgetBarChartContainer.addWidget(self.widget_showManagerInfo)
        self.layout_widgetBarChartContainer.setStretch(0, 3)
        self.layout_widgetBarChartContainer.setStretch(1, 1)
        self.layout_chartMain.addWidget(self.widget_barChart_container)
        self.layout_bottom.addLayout(self.layout_chartMain)
        self.layout_chartMain.setStretch(0,1)
        self.layout_chartMain.setStretch(1,1)


        '''date info part'''
        self.widget_showDate_container = QtWidgets.QWidget(Proc_MainPage)
        self.widget_showDate_container.setObjectName("widget_showDate_container")
        self.layout_showDateMain = QtWidgets.QVBoxLayout(self.widget_showDate_container)
        self.layout_showDateMain.setSpacing(10)
        self.layout_showDateMain.setObjectName("layout_showDateMain")
        self.widget_showCurDate = QtWidgets.QWidget(self.widget_showDate_container)
        self.widget_showCurDate.setObjectName("widget_showCurDate")
        self.layout_widget_showCurDate = QtWidgets.QVBoxLayout(self.widget_showCurDate)
        self.layout_widget_showCurDate.setObjectName("layout_widget_showCurDate")

        '''label to show month img'''
        self.label_showDate_month = QtWidgets.QLabel(self.widget_showCurDate)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_showDate_month.setFont(font)
        self.label_showDate_month.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showDate_month.setObjectName("label_showDate_month")
        self.layout_widget_showCurDate.addWidget(self.label_showDate_month)


        self.widget_showDate_day = Uni_ShowDateInfo_Widget()
        self.widget_showDate_day.setObjectName("widget_showDate_day")

        self.layout_widget_showCurDate.addWidget(self.widget_showDate_day)
        self.layout_widget_showCurDate.setStretch(0, 1)
        self.layout_widget_showCurDate.setStretch(1, 1)
        self.layout_showDateMain.addWidget(self.widget_showCurDate)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget_showDate_container)
        self.calendarWidget.setObjectName("calendarWidget")


        '''layout setting'''
        self.layout_showDateMain.addWidget(self.calendarWidget)
        self.layout_showDateMain.setStretch(0, 3)
        self.layout_showDateMain.setStretch(1, 2)
        self.layout_bottom.addWidget(self.widget_showDate_container)
        self.layout_bottom.setStretch(0, 5)
        self.layout_bottom.setStretch(1, 2)
        self.verticalLayout.addLayout(self.layout_bottom)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)

        '''enhance shadow effects'''
        self.setShadowEffects(self.widget_topBar_container,"rgba(0,191,255,90)")
        self.setShadowEffects(self.widget_topBar_checkedNum,"rgba(255,255,255,90)")
        self.setShadowEffects(self.widget_topBar_personChgNum,"rgba(255,255,255,90)")
        self.setShadowEffects(self.widget_topBar_totalNum,"rgba(255,255,255,90)")
        self.setShadowEffects(self.widget_topBar_requestNum,"rgba(255,255,255,90)")
        self.setShadowEffects(self.widget_showCurDate,"rgba(255,255,255,90)")

        self.setShadowEffects(self.widget_showDate_container,"rgba(127,255,0,90)")
        self.setShadowEffects(self.widget_pieChart_container,"rgba(255,215,0,90)")
        self.setShadowEffects(self.widget_barChart_container,"rgba(255,69,0,90)")

        self.setShadowEffects(self.widget_showManagerInfo,"rgba(255,255,255,90)")

        '''set calendar style'''
        self.calendarWidget.currentPageChanged['int','int'].connect(Proc_MainPage.pageChange)
        with open("Qss/flatwhite_style.qss") as CalendarStyle:
            self.calendarWidget.setStyleSheet(CalendarStyle.read())

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        #font.setBold(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QCalendarWidget.NoVerticalHeader)

        '''set line edit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.LEdit_showManagerName.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_showManegerId.setStyleSheet(LEditStyle.read())
            # LEditStyle.seek(0)

        self.LEdit_showManagerName.setReadOnly(True)
        self.LEdit_showManegerId.setReadOnly(True)

        self.retranslateUi(Proc_MainPage)
        QtCore.QMetaObject.connectSlotsByName(Proc_MainPage)

    def retranslateUi(self, Proc_MainPage):
        _translate = QtCore.QCoreApplication.translate
        Proc_MainPage.setWindowTitle(_translate("Proc_MainPage", "Form"))
        self.label_topBar_totalNum_title.setText(_translate("Proc_MainPage", 
            """<html><body><img src="icons/icon_manager/ren.png" width="40", height="40"><p>公司员工数</p></body></html>"""))
        self.label_topBar_totalNum_num.setText(_translate("Proc_MainPage", "0"))
        self.label_topBar_checkedNum_title.setText(_translate("Proc_MainPage", 
            """<html><body><img src="icons/icon_manager/buqian.png" width="40", height="40"><p><p>今日签到数</p></body></html>"""))
        self.label_topBar_checkedNum_num.setText(_translate("Proc_MainPage", "0"))
        self.label_topBar_requestNum_title.setText(_translate("Proc_MainPage", 
            """<html><body><img src="icons/icon_manager/jiaban.png" width="40", height="40"><p>待处理请求</p></body></html>"""))
        self.label_topBar_requestNum_num.setText(_translate("Proc_MainPage", "0"))
        self.label_topBar_personChgNum_title.setText(_translate("Proc_MainPage",     
        """<html><body><img src="icons/icon_manager/lizhijiaojie.png" width="40", height="40"><p>人员变动</p></body></html>"""))
        self.label_topBar_personChgNum_num.setText(_translate("Proc_MainPage", "0"))
        self.label_showManagerName.setText(_translate("Proc_MainPage", "管理者名字:"))
        self.label_showManagerId.setText(_translate("Proc_MainPage", "管理者ID:"))
        self.label_showDate_month.setText(_translate("Proc_MainPage", "MonthLabel"))

    def setShadowEffects(self, widget, rgba="rgba(255, 255, 255, 130)"):
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        widget.setGraphicsEffect(shadow_effect)
        widget.setStyleSheet("""QWidget#"""+widget.objectName()+"""{
                                background-color: """+rgba+""";
                                border-radius: 8px}""")

if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    TestUi.main_ui=Ui_Proc_MainPage()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )