# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proc_showcompdata_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_Proc_ShowCompData(object):
    def setupUi(self, Proc_ShowCompData):
        Proc_ShowCompData.setObjectName("Proc_ShowCompData")
        Proc_ShowCompData.resize(592, 226)
        self.gridLayout_2 = QtWidgets.QGridLayout(Proc_ShowCompData)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_container = QtWidgets.QWidget(Proc_ShowCompData)
        self.widget_container.setObjectName("widget_container")
        self.layout_main = QtWidgets.QGridLayout(self.widget_container)
        self.layout_main.setObjectName("layout_main")
        self.layout_showData = QtWidgets.QGridLayout()
        self.layout_showData.setObjectName("layout_showData")
        self.label_showBottomRank = QtWidgets.QLabel(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_showBottomRank.setFont(font)
        self.label_showBottomRank.setObjectName("label_showBottomRank")
        self.layout_showData.addWidget(self.label_showBottomRank, 1, 0, 1, 1)
        self.label_showAverageBreak = QtWidgets.QLabel(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_showAverageBreak.setFont(font)
        self.label_showAverageBreak.setObjectName("label_showAverageBreak")
        self.layout_showData.addWidget(self.label_showAverageBreak, 3, 0, 1, 1)
        self.label_showAverageCheck = QtWidgets.QLabel(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_showAverageCheck.setFont(font)
        self.label_showAverageCheck.setObjectName("label_showAverageCheck")
        self.layout_showData.addWidget(self.label_showAverageCheck, 2, 0, 1, 1)
        self.label_showTopRank = QtWidgets.QLabel(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_showTopRank.setFont(font)
        self.label_showTopRank.setObjectName("label_showTopRank")
        self.layout_showData.addWidget(self.label_showTopRank, 0, 0, 1, 1)
        self.lineEdit_showTopRank = QtWidgets.QLineEdit(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_showTopRank.setFont(font)
        self.lineEdit_showTopRank.setObjectName("lineEdit_showTopRank")
        self.layout_showData.addWidget(self.lineEdit_showTopRank, 0, 1, 1, 1)
        self.lineEdit_showBottomRank = QtWidgets.QLineEdit(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_showBottomRank.setFont(font)
        self.lineEdit_showBottomRank.setObjectName("lineEdit_showBottomRank")
        self.layout_showData.addWidget(self.lineEdit_showBottomRank, 1, 1, 1, 1)
        self.lineEdit_showAverageCheck = QtWidgets.QLineEdit(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_showAverageCheck.setFont(font)
        self.lineEdit_showAverageCheck.setObjectName("lineEdit_showAverageCheck")
        self.layout_showData.addWidget(self.lineEdit_showAverageCheck, 2, 1, 1, 1)
        self.lineEdit_showAverageBreak = QtWidgets.QLineEdit(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_showAverageBreak.setFont(font)
        self.lineEdit_showAverageBreak.setObjectName("lineEdit_showAverageBreak")
        self.layout_showData.addWidget(self.lineEdit_showAverageBreak, 3, 1, 1, 1)
        self.layout_main.addLayout(self.layout_showData, 1, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(self.widget_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        
        '''layout settings'''
        self.layout_main.addWidget(self.label_title, 0, 0, 1, 1)
        self.layout_main.setRowStretch(0, 3)
        self.layout_main.setRowStretch(1, 8)
        self.gridLayout_2.addWidget(self.widget_container, 0, 0, 1, 1)


        '''set lineedit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.lineEdit_showAverageBreak.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEdit_showAverageCheck.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEdit_showBottomRank.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEdit_showTopRank.setStyleSheet(LEditStyle.read())
            # LEditStyle.seek(0)

        self.lineEdit_showAverageBreak.setReadOnly(True)
        self.lineEdit_showAverageCheck.setReadOnly(True)
        self.lineEdit_showBottomRank.setReadOnly(True)
        self.lineEdit_showTopRank.setReadOnly(True)

        '''enhance shadow effect'''
        # shadow_effect=QGraphicsDropShadowEffect()
        # shadow_effect.setOffset(0,0)
        # shadow_effect.setColor(QColor("#444444"))
        # shadow_effect.setBlurRadius(5)
        # self.widget_container.setGraphicsEffect(shadow_effect)

        self.retranslateUi(Proc_ShowCompData)
        QtCore.QMetaObject.connectSlotsByName(Proc_ShowCompData)



    def retranslateUi(self, Proc_ShowCompData):
        _translate = QtCore.QCoreApplication.translate
        Proc_ShowCompData.setWindowTitle(_translate("Proc_ShowCompData", "Form"))
        self.label_showBottomRank.setText(_translate("Proc_ShowCompData", "本月排名最低员工:"))
        self.label_showAverageBreak.setText(_translate("Proc_ShowCompData", "本月平均请假率:"))
        self.label_showAverageCheck.setText(_translate("Proc_ShowCompData", "本月平均考勤率:"))
        self.label_showTopRank.setText(_translate("Proc_ShowCompData", "本月排名最高员工:"))
        self.label_title.setText(_translate("Proc_ShowCompData", "公司员工平均数据:"))



if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    #TestUi.setWindowFlags (Qt.FramelessWindowHint)
    TestUi.main_ui=Ui_Proc_ShowCompData()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )

