# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proc_login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtChart import *

class Ui_Proc_Login(object):
    def setupUi(self, Proc_Login):
        Proc_Login.setObjectName("Proc_Login")
        Proc_Login.resize(453, 545)
        self.layout_main = QtWidgets.QGridLayout(Proc_Login)
        self.layout_main.setContentsMargins(13, 13, 13, 13)
        self.layout_main.setHorizontalSpacing(7)
        self.layout_main.setVerticalSpacing(12)
        self.layout_main.setObjectName("layout_main")
        self.widget_top_container = QtWidgets.QWidget(Proc_Login)
        self.widget_top_container.setObjectName("widget_top_container")
        self.layout_widgetTopContainer = QtWidgets.QGridLayout(self.widget_top_container)
        self.layout_widgetTopContainer.setObjectName("layout_widgetTopContainer")
        self.label_showTitle = QtWidgets.QLabel(self.widget_top_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_showTitle.setFont(font)
        self.label_showTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showTitle.setObjectName("label_showTitle")
        self.layout_widgetTopContainer.addWidget(self.label_showTitle, 0, 0, 1, 1)
        self.layout_main.addWidget(self.widget_top_container, 0, 0, 1, 1)
        self.widget_bottom_container = QtWidgets.QWidget(Proc_Login)
        self.widget_bottom_container.setObjectName("widget_bottom_container")
        self.layout_widgetBottomContainer = QtWidgets.QGridLayout(self.widget_bottom_container)
        self.layout_widgetBottomContainer.setObjectName("layout_widgetBottomContainer")
        self.layout_btnLogin = QtWidgets.QHBoxLayout()
        self.layout_btnLogin.setObjectName("layout_btnLogin")
        self.layout_getinfo_outside = QtWidgets.QVBoxLayout()
        self.layout_getinfo_outside.setObjectName("layout_getinfo_outside")
        self.layout_getInfo_inside = QtWidgets.QGridLayout()
        self.layout_getInfo_inside.setObjectName("layout_getInfo_inside")
        self.label_getId_title = QtWidgets.QLabel(self.widget_bottom_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_getId_title.setFont(font)
        self.label_getId_title.setObjectName("label_getId_title")
        self.layout_getInfo_inside.addWidget(self.label_getId_title, 0, 0, 1, 1)
        self.lineEdit_getId = QtWidgets.QLineEdit(self.widget_bottom_container)
        self.lineEdit_getId.setObjectName("lineEdit_getId")
        self.layout_getInfo_inside.addWidget(self.lineEdit_getId, 0, 1, 1, 1)
        self.label_getPassword_title = QtWidgets.QLabel(self.widget_bottom_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_getPassword_title.setFont(font)
        self.label_getPassword_title.setObjectName("label_getPassword_title")
        self.layout_getInfo_inside.addWidget(self.label_getPassword_title, 1, 0, 1, 1)
        self.lineEdit_getPassword = QtWidgets.QLineEdit(self.widget_bottom_container)
        self.lineEdit_getPassword.setObjectName("lineEdit_getPassword")
        self.layout_getInfo_inside.addWidget(self.lineEdit_getPassword, 1, 1, 1, 1)
        self.layout_getInfo_inside.setRowStretch(0, 2)
        self.layout_getinfo_outside.addLayout(self.layout_getInfo_inside)
        self.layout_btnFindPw = QtWidgets.QHBoxLayout()
        self.layout_btnFindPw.setObjectName("layout_btnFindPw")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_btnFindPw.addItem(spacerItem)
        self.btn_findPw = QtWidgets.QPushButton(self.widget_bottom_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.btn_findPw.setFont(font)
        self.btn_findPw.setObjectName("btn_findPw")
        self.layout_btnFindPw.addWidget(self.btn_findPw)
        self.layout_getinfo_outside.addLayout(self.layout_btnFindPw)
        self.layout_btnLogin.addLayout(self.layout_getinfo_outside)
        self.layout_widgetBottomContainer.addLayout(self.layout_btnLogin, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.layout_widgetBottomContainer.addItem(spacerItem1, 3, 0, 1, 1)

        self.layout_bottomBtn=QHBoxLayout()

        self.btn_signin=QtWidgets.QPushButton(self.widget_bottom_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_signin.setFont(font)
        self.btn_signin.setObjectName("btn_signin")
        self.layout_bottomBtn.addWidget(self.btn_signin)

        self.btn_login = QtWidgets.QPushButton(self.widget_bottom_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.layout_bottomBtn.addWidget(self.btn_login)

        self.layout_bottomBtn.setSpacing(10)

        '''set layout'''
        self.layout_widgetBottomContainer.addItem(self.layout_bottomBtn, 4, 0, 1, 1)
        self.layout_widgetBottomContainer.setRowStretch(2, 2)
        self.layout_widgetBottomContainer.setRowStretch(3, 1)
        self.layout_widgetBottomContainer.setRowStretch(4, 2)
        self.layout_main.addWidget(self.widget_bottom_container, 1, 0, 1, 1)

        '''set btn style'''
        with open("Qss/push_button_style.qss") as BtnStyle:
            self.btn_login.setStyleSheet(BtnStyle.read())
        with open("Qss/push_button_style_fw.qss") as BtnStyle:
            self.btn_findPw.setStyleSheet(BtnStyle.read())
        with open("Qss/push_button_style_lightblue.qss") as BtnStyle:
            self.btn_signin.setStyleSheet(BtnStyle.read())

        '''set line edit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.lineEdit_getId.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.lineEdit_getPassword.setStyleSheet(LEditStyle.read())
            # LEditStyle.seek(0)

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        self.lineEdit_getId.setFont(font)
        self.lineEdit_getPassword.setFont(font)

        regx=QtCore.QRegExp("[0-9]+$")
        validator=QtGui.QRegExpValidator(regx, self.lineEdit_getId)
        self.lineEdit_getId.setValidator(validator)
        regx=QtCore.QRegExp("[0-9]+$")
        validator=QtGui.QRegExpValidator(regx, self.lineEdit_getPassword)
        self.lineEdit_getPassword.setValidator(validator)

        '''enhance shadow effect'''
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_bottom_container.setGraphicsEffect(shadow_effect)
        self.widget_bottom_container.setStyleSheet("""QWidget#widget_bottom_container{
                                                    background-color: rgba(255,255,255,140);
                                                    border-radius: 8px}""")
        
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_top_container.setGraphicsEffect(shadow_effect)

        '''set connection'''
        self.btn_findPw.clicked.connect(Proc_Login.slot_FindPassword)
        self.btn_login.clicked.connect(Proc_Login.slot_LogIn)
        self.btn_signin.clicked.connect(Proc_Login.slot_SignIn)

        self.retranslateUi(Proc_Login)
        QtCore.QMetaObject.connectSlotsByName(Proc_Login)

    def retranslateUi(self, Proc_Login):
        _translate = QtCore.QCoreApplication.translate
        Proc_Login.setWindowTitle(_translate("Proc_Login", "Form"))
        self.label_showTitle.setText(_translate("Proc_Login", """<html><body></body><img src= "image/proc_mainimg.png"  
            height="190",width="190"><p>996监督考勤系统--登录</p></body></html>"""))
        self.label_getId_title.setText(_translate("Proc_Login", "账号:"))
        self.label_getPassword_title.setText(_translate("Proc_Login", "密码:"))
        self.btn_findPw.setText(_translate("Proc_Login", "找回密码"))
        self.btn_signin.setText(_translate("Proc_Login", "注册"))
        self.btn_login.setText(_translate("Proc_Login", "登录"))

if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    TestUi.main_ui=Ui_Proc_Login()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )