# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uni_showDateInfo_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_widget_showDateInfo(object):
    def setupUi(self, widget_showDateInfo):
        widget_showDateInfo.setObjectName("widget_showDateInfo")
        widget_showDateInfo.resize(510, 179)
        self.main_layout = QtWidgets.QHBoxLayout(widget_showDateInfo)
        self.main_layout.setObjectName("main_layout")
        self.widget_showToday_container = QtWidgets.QWidget(widget_showDateInfo)
        self.widget_showToday_container.setObjectName("widget_showToday_container")
        self.layout_widgetShowTodayContainer = QtWidgets.QVBoxLayout(self.widget_showToday_container)
        self.layout_widgetShowTodayContainer.setObjectName("layout_widgetShowTodayContainer")
        self.label_showToday_title = QtWidgets.QLabel(self.widget_showToday_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_showToday_title.setFont(font)
        self.label_showToday_title.setObjectName("label_showToday_title")
        self.layout_widgetShowTodayContainer.addWidget(self.label_showToday_title)
        self.label_showToday_date = QtWidgets.QLabel(self.widget_showToday_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_showToday_date.setFont(font)
        self.label_showToday_date.setObjectName("label_showToday_date")
        self.layout_widgetShowTodayContainer.addWidget(self.label_showToday_date)
        self.layout_widgetShowTodayContainer.setStretch(0, 2)
        self.layout_widgetShowTodayContainer.setStretch(1, 3)
        self.main_layout.addWidget(self.widget_showToday_container)
        self.line = QtWidgets.QFrame(widget_showDateInfo)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_layout.addWidget(self.line)
        self.widget_showWeather_container = QtWidgets.QWidget(widget_showDateInfo)
        self.widget_showWeather_container.setObjectName("widget_showWeather_container")
        self.layout_widgetShowWeatherContainer = QtWidgets.QVBoxLayout(self.widget_showWeather_container)
        self.layout_widgetShowWeatherContainer.setObjectName("layout_widgetShowWeatherContainer")
        self.label_showweather_city = QtWidgets.QLabel(self.widget_showWeather_container)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(50)
        self.label_showweather_city.setFont(font)
        self.label_showweather_city.setObjectName("label_showweather_city")
        self.layout_widgetShowWeatherContainer.addWidget(self.label_showweather_city)
        self.label_showWeather_img = QtWidgets.QLabel(self.widget_showWeather_container)
        self.label_showWeather_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_showWeather_img.setObjectName("label_showWeather_img")
        self.layout_widgetShowWeatherContainer.addWidget(self.label_showWeather_img)
        self.layout_widgetShowWeatherContainer.setStretch(0, 1)
        self.layout_widgetShowWeatherContainer.setStretch(1, 3)
        self.main_layout.addWidget(self.widget_showWeather_container)

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        widget_showDateInfo.setGraphicsEffect(shadow_effect)
        widget_showDateInfo.setStyleSheet("""QWidget#widget_showDateInfo{
                                                    background-color: rgba(255,255,255, 90);
                                                    border-radius: 8px}""")

        self.retranslateUi(widget_showDateInfo)
        QtCore.QMetaObject.connectSlotsByName(widget_showDateInfo)

    def retranslateUi(self, widget_showDateInfo):
        _translate = QtCore.QCoreApplication.translate
        widget_showDateInfo.setWindowTitle(_translate("widget_showDateInfo", "Form"))
        self.label_showToday_title.setText(_translate("widget_showDateInfo", "<html><head/><body><p><span style=\" font-style:italic;\">Today：</span></p></body></html>"))
        self.label_showToday_date.setText(_translate("widget_showDateInfo", ""))
        self.label_showweather_city.setText(_translate("widget_showDateInfo", "city, temp"))
        self.label_showWeather_img.setText(_translate("widget_showDateInfo", "show weather img"))

if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    TestUi.setWindowFlags (Qt.FramelessWindowHint)
    TestUi.main_ui=Ui_widget_showDateInfo()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )