# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BreakDayApply.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import pymysql
import socket
import time
import json
host=socket.gethostname()
port=9999
from client import breakget,complainget,breakdayapply,complainapply
class Ui_BreakDayApply(object):
    def setupUi(self, BreakDayApply):
        BreakDayApply.setObjectName("BreakDayApply")
        BreakDayApply.resize(597, 643)
        BreakDayApply.setStyleSheet("")
        BreakDayApply.setStyleSheet("""QWidget#CheckIn_Show{
                                    alternate-background-color: rgba(225, 225, 225);
                                    border-bottom-right-radius: 10px;
                                    border-bottom-left-radius: 10px;}""")
        
        '''main layout'''
        self.gridLayout_4 = QtWidgets.QGridLayout(BreakDayApply)
        self.gridLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")

        '''top part -- get id and name'''
        self.widget_getBasicInfo = QtWidgets.QWidget(BreakDayApply)
        self.widget_getBasicInfo.setObjectName("widget_getBasicInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_getBasicInfo)
        self.gridLayout.setContentsMargins(5, 5, 5, 10)
        self.gridLayout.setObjectName("gridLayout")

        '''get id ui'''
        self.layout_getId = QtWidgets.QHBoxLayout()
        self.layout_getId.setObjectName("layout_getId")
        self.label_getid = QtWidgets.QLabel(self.widget_getBasicInfo)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_getid.setFont(font)
        self.label_getid.setObjectName("label_getid")
        self.layout_getId.addWidget(self.label_getid)
        self.LEdit_getId = QtWidgets.QLineEdit(self.widget_getBasicInfo)
        self.LEdit_getId.setObjectName("LEdit_getId")
        self.layout_getId.addWidget(self.LEdit_getId)
        self.gridLayout.addLayout(self.layout_getId, 0, 0, 1, 1)

        '''get name ui'''
        self.layout_getName = QtWidgets.QHBoxLayout()
        self.layout_getName.setObjectName("layout_getName")
        self.label_getname = QtWidgets.QLabel(self.widget_getBasicInfo)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_getname.setFont(font)
        self.label_getname.setStyleSheet("")
        self.label_getname.setObjectName("label_getname")
        self.layout_getName.addWidget(self.label_getname)
        self.LEdit_getName = QtWidgets.QLineEdit(self.widget_getBasicInfo)
        self.LEdit_getName.setObjectName("LEdit_getName")
        self.layout_getName.addWidget(self.LEdit_getName)
        self.gridLayout.addLayout(self.layout_getName, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_getBasicInfo, 0, 0, 1, 1)

        '''middle part -- get break time'''
        self.widget_getBreakTime = QtWidgets.QWidget(BreakDayApply)
        self.widget_getBreakTime.setObjectName("widget_getBreakTime")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_getBreakTime)
        self.gridLayout_2.setContentsMargins(5, 10, 5, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")

        '''get start time'''
        self.layout_starttime = QtWidgets.QHBoxLayout()
        self.layout_starttime.setObjectName("layout_starttime")
        self.label_getStartTime = QtWidgets.QLabel(self.widget_getBreakTime)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_getStartTime.setFont(font)
        self.label_getStartTime.setObjectName("label_getStartTime")
        self.layout_starttime.addWidget(self.label_getStartTime)
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.widget_getBreakTime)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.layout_starttime.addWidget(self.dateTimeEdit_start)
        self.gridLayout_2.addLayout(self.layout_starttime, 0, 0, 1, 1)

        '''get stop time'''
        self.layout_deadline = QtWidgets.QHBoxLayout()
        self.layout_deadline.setObjectName("layout_deadline")
        self.label_getEndTime = QtWidgets.QLabel(self.widget_getBreakTime)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_getEndTime.setFont(font)
        self.label_getEndTime.setStyleSheet("")
        self.label_getEndTime.setObjectName("label_getEndTime")
        self.layout_deadline.addWidget(self.label_getEndTime)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.widget_getBreakTime)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.layout_deadline.addWidget(self.dateTimeEdit_2)
        self.gridLayout_2.addLayout(self.layout_deadline, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_getBreakTime, 1, 0, 1, 1)

        '''bottom part --  get reason'''
        self.widget_getReason = QtWidgets.QWidget(BreakDayApply)
        self.widget_getReason.setObjectName("widget_getReason")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_getReason)
        self.gridLayout_3.setContentsMargins(5, 10, 5, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")

        '''get reason text ui'''
        self.txtEdit_getReason = QtWidgets.QTextEdit(self.widget_getReason)
        self.txtEdit_getReason.setObjectName("txtEdit_getReason")
        self.gridLayout_3.addWidget(self.txtEdit_getReason, 2, 0, 1, 1)
        self.label_getReason = QtWidgets.QLabel(self.widget_getReason)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_getReason.setFont(font)
        self.label_getReason.setObjectName("label_getReason")
        self.gridLayout_3.addWidget(self.label_getReason, 1, 0, 1, 1)

        # btn to apply
        self.layout_setbtn = QtWidgets.QHBoxLayout()
        self.layout_setbtn.setObjectName("layout_setbtn")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_setbtn.addItem(spacerItem)
        self.btn_apply = QtWidgets.QPushButton(self.widget_getReason)
        self.btn_apply.setMaximumSize(QtCore.QSize(200, 62))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_apply.setFont(font)
        self.btn_apply.setStyleSheet("")
        self.btn_apply.setObjectName("btn_apply")
        self.layout_setbtn.addWidget(self.btn_apply)

        # btn to cancel
        self.btn_cancel = QtWidgets.QPushButton(self.widget_getReason)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.layout_setbtn.addWidget(self.btn_cancel)


        self.gridLayout_3.addLayout(self.layout_setbtn, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_getReason, 2, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 2)
        self.gridLayout_4.setRowStretch(2, 10)

        '''set button style'''
        with open("Qss/push_button_style.qss") as BtnStyle:
            self.btn_apply.setStyleSheet(BtnStyle.read())
        with open("Qss/push_button_style_lightblue.qss") as BtnStyle:
            self.btn_cancel.setStyleSheet(BtnStyle.read())

        '''set lineedit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.LEdit_getId.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_getName.setStyleSheet(LEditStyle.read())

        '''set date edit style'''
        with open("Qss/datetime_edit_style.qss") as DTEditStyle:
            self.dateTimeEdit_start.setStyleSheet(DTEditStyle.read())
            DTEditStyle.seek(0)
            self.dateTimeEdit_2.setStyleSheet(DTEditStyle.read())

        '''set txt edit style'''
        with open("Qss/textedit_style.qss") as TxtStyle:
            self.txtEdit_getReason.setStyleSheet(TxtStyle.read())

        '''enhance shadow effect'''
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_getBasicInfo.setGraphicsEffect(shadow_effect)
        self.widget_getBasicInfo.setStyleSheet("""QWidget#widget_getBasicInfo{
                                                    background-color: rgba(255,255,255,180);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_getBreakTime.setGraphicsEffect(shadow_effect)
        self.widget_getBreakTime.setStyleSheet("""QWidget#widget_getBreakTime{
                                                    background-color: rgba(255,255,255,180);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_getReason.setGraphicsEffect(shadow_effect)
        self.widget_getReason.setStyleSheet("""QWidget#widget_getReason{
                                                    background-color: rgba(255,255,255,180);
                                                    border-radius: 8px}""")


        self.retranslateUi(BreakDayApply)
        self.btn_apply.clicked.connect(BreakDayApply.btnapply)
        self.btn_cancel.clicked.connect(BreakDayApply.btncancel)
        QtCore.QMetaObject.connectSlotsByName(BreakDayApply)
        self.btn_apply.clicked.connect(self.get)
        self.btn_cancel.clicked.connect(self.cancel)

    def get(self, BreakDayApply):
        datetime_start=self.dateTimeEdit_start.dateTime()
        datetime_end=self.dateTimeEdit_2.dateTime()
        strText = self.txtEdit_getReason.toPlainText()
        strid = self.LEdit_getId.text()
        strname = self.LEdit_getName.text()
        datetime_start=datetime_start.toString("yyyy-MM-dd hh:mm:ss")
        datetime_end=datetime_end.toString("yyyy-MM-dd hh:mm:ss")
        print(strText)
        print(strid)
        print(strname)
        print(datetime_start)
        print(datetime_end)
        info=[]
        info.append(strid)
        info.append(strname)
        info.append(datetime_start)
        info.append(datetime_end)
        info.append(strText)
        info=json.dumps(info)#转为 json
        BreakDayApply.breakdayapply(info)
#       result=json.loads(result)
        print("接收成功，准备返回")
        return


        
    def cancel(self, BreakDayApply):
        self.txtEdit_getReason.setText("")
        self.LEdit_getId.setText("")
        self.LEdit_getName.setText("")

    def retranslateUi(self, BreakDayApply):
        _translate = QtCore.QCoreApplication.translate
        BreakDayApply.setWindowTitle(_translate("BreakDayApply", "Form"))
        self.label_getid.setText(_translate("BreakDayApply", "员工ID"))
        self.label_getname.setText(_translate("BreakDayApply", "姓名"))
        self.label_getStartTime.setText(_translate("BreakDayApply", "请假开始时间"))
        self.label_getEndTime.setText(_translate("BreakDayApply", "请假结束时间"))
        self.label_getReason.setText(_translate("BreakDayApply", "请假理由叙述"))
        self.btn_apply.setText(_translate("BreakDayApply", "提交申请"))
        self.btn_cancel.setText(_translate("BreakDayApply", "清除"))


if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    TestUi.main_ui=Ui_BreakDayApply()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )