# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckIn_Show.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_CheckIn_Show(object):
    def setupUi(self, CheckIn_Show):
        CheckIn_Show.setObjectName("CheckIn_Show")
        CheckIn_Show.resize(800, 800)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        CheckIn_Show.setFont(font)
        CheckIn_Show.setStyleSheet("""QWidget#CheckIn_Show{
                                    border-bottom-right-radius: 10px;
                                    border-bottom-left-radius: 10px;}""")

        '''main layout of window''' 
        self.gridLayout_2 = QtWidgets.QGridLayout(CheckIn_Show)
        self.gridLayout_2.setObjectName("gridLayout_2")

        '''top part'''
        self.numberGet_container_widget = QtWidgets.QWidget(CheckIn_Show)
        self.numberGet_container_widget.setObjectName("numberGet_container_widget")
        
        '''main vertical layout of numberGet_container_widget'''
        self.verticalLayout = QtWidgets.QVBoxLayout(self.numberGet_container_widget)
        self.verticalLayout.setObjectName("verticalLayout")

        '''number get layout (for label and lineedit)'''
        self.numberGet_layout = QtWidgets.QHBoxLayout()
        self.numberGet_layout.setObjectName("numberGet_layout")
        # label
        self.labelTipID = QtWidgets.QLabel(self.numberGet_container_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(True)
        self.labelTipID.setFont(font)
        self.labelTipID.setObjectName("labelTipID")
        self.numberGet_layout.addWidget(self.labelTipID)
        # line edit
        self.lineEditGetID = QtWidgets.QLineEdit(self.numberGet_container_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGetID.sizePolicy().hasHeightForWidth())
        self.lineEditGetID.setSizePolicy(sizePolicy)
        self.lineEditGetID.setStyleSheet("")
        self.lineEditGetID.setObjectName("lineEditGetID")
        self.numberGet_layout.addWidget(self.lineEditGetID)
        self.numberGet_layout.setStretch(0, 3)
        self.numberGet_layout.setStretch(1, 4)
        self.verticalLayout.addLayout(self.numberGet_layout)

        '''layout for start button'''
        self.btnStart_layout = QtWidgets.QHBoxLayout()
        self.btnStart_layout.setObjectName("btnStart_layout")
        # spacer item
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btnStart_layout.addItem(spacerItem)
        # btn to start
        self.pushButtonSure = QtWidgets.QPushButton(self.numberGet_container_widget)
        self.pushButtonSure.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButtonSure.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.pushButtonSure.setFont(font)
        self.pushButtonSure.setStyleSheet("")
        self.pushButtonSure.setObjectName("pushButtonSure")
        self.btnStart_layout.addWidget(self.pushButtonSure)
        self.verticalLayout.addLayout(self.btnStart_layout)

        self.gridLayout_2.addWidget(self.numberGet_container_widget, 0, 0, 1, 1)
        
        '''bottom part'''
        self.msgGet_container_widget = QtWidgets.QWidget(CheckIn_Show)
        self.msgGet_container_widget.setObjectName("msgGet_container_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.msgGet_container_widget)
        self.gridLayout.setObjectName("gridLayout")

        '''position to place camera video'''
        self.labelShowCamera = QtWidgets.QLabel(self.msgGet_container_widget)
        font = QtGui.QFont()
        font.setFamily("Adobe 仿宋 Std R")
        font.setPointSize(36)
        self.labelShowCamera.setFont(font)
        self.labelShowCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShowCamera.setObjectName("labelShowCamera")
        
        self.gridLayout.addWidget(self.labelShowCamera, 0, 0, 1, 1)
        
        '''position to place number and it's tip label'''
        self.showNumber_layout = QtWidgets.QHBoxLayout()
        self.showNumber_layout.setObjectName("showNumber_layout")
        # label to show tip
        self.labelTipText = QtWidgets.QLabel(self.msgGet_container_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.labelTipText.setFont(font)

        self.labelTipText.setStyleSheet("")
        self.labelTipText.setObjectName("labelTipText")
        self.showNumber_layout.addWidget(self.labelTipText)
        # label to show numbers
        self.labelShowNum = QtWidgets.QLabel(self.msgGet_container_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelShowNum.setFont(font)
        self.labelShowNum.setObjectName("labelShowNum")
        self.showNumber_layout.addWidget(self.labelShowNum)

        '''set layouts'''
        self.gridLayout.addLayout(self.showNumber_layout, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout_2.addWidget(self.msgGet_container_widget, 1, 0, 1, 1)

        '''enhance shadow effect'''
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.msgGet_container_widget.setGraphicsEffect(shadow_effect)
        self.msgGet_container_widget.setStyleSheet("""QWidget#msgGet_container_widget{
                                                    background-color: rgba(250,250,250,230);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.numberGet_container_widget.setGraphicsEffect(shadow_effect)
        self.numberGet_container_widget.setStyleSheet("""QWidget#numberGet_container_widget{
                                                    background-color: rgba(250,250,250,230); 
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.labelShowCamera.setStyleSheet("background-color: rgba(255, 255, 255, 200)")
        self.labelShowCamera.setGraphicsEffect(shadow_effect)
        self.gridLayout.setContentsMargins(5,5,5,5)
        
        '''set btn style'''
        with open("Qss/push_button_style_lightblue.qss") as BtnStyle:
            self.pushButtonSure.setStyleSheet(BtnStyle.read())

        '''set lineedit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.lineEditGetID.setStyleSheet(LEditStyle.read())

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.lineEditGetID.setFont(font)

        regx=QtCore.QRegExp("[0-9]+$")
        validator=QtGui.QRegExpValidator(regx, self.lineEditGetID)
        self.lineEditGetID.setValidator(validator)

        self.retranslateUi(CheckIn_Show)
        self.pushButtonSure.clicked.connect(CheckIn_Show.turnToGetVideo)
        QtCore.QMetaObject.connectSlotsByName(CheckIn_Show)

    def retranslateUi(self, CheckIn_Show):
        _translate = QtCore.QCoreApplication.translate
        CheckIn_Show.setWindowTitle(_translate("CheckIn_Show", "Form"))
        self.labelTipID.setText(_translate("CheckIn_Show", "请输入您的工号"))
        self.pushButtonSure.setText(_translate("CheckIn_Show", "开始签到"))
        self.labelShowCamera.setText(_translate("CheckIn_Show", "摄像头在此"))
        self.labelTipText.setText(_translate("CheckIn_Show", "请说出下面的数字:"))
        self.labelShowNum.setText(_translate("CheckIn_Show", "123456"))
