# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'complain_apply_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import pymysql
import socket
import time
import json
from client import breakget,complainget,breakdayapply,complainapply
host=socket.gethostname()
port=9999
global strreason
strreason="原因未选择"
class Ui_Complain_Apply_Ui(object):
    def setupUi(self, complain_apply_ui):
        complain_apply_ui.setObjectName("complain_apply_ui")
        complain_apply_ui.resize(596, 680)

        '''main layout'''
        self.gridLayout_4 = QtWidgets.QGridLayout(complain_apply_ui)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setHorizontalSpacing(9)
        self.gridLayout_4.setVerticalSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")

        '''top part -- get staff basic info'''
        self.widget_getBasicInfo = QtWidgets.QWidget(complain_apply_ui)
        self.widget_getBasicInfo.setObjectName("widget_getBasicInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_getBasicInfo)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")

        '''get staff name'''
        self.layout_getName = QtWidgets.QHBoxLayout()
        self.layout_getName.setObjectName("layout_getName")
        self.label_getName = QtWidgets.QLabel(self.widget_getBasicInfo)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_getName.setFont(font)
        self.label_getName.setObjectName("label_getName")
        self.layout_getName.addWidget(self.label_getName)
        self.LEdit_getName = QtWidgets.QLineEdit(self.widget_getBasicInfo)
        self.LEdit_getName.setObjectName("LEdit_getName")
        self.layout_getName.addWidget(self.LEdit_getName)
        self.gridLayout.addLayout(self.layout_getName, 0, 1, 1, 1)

        '''get staff id'''
        self.layout_getId = QtWidgets.QHBoxLayout()
        self.layout_getId.setObjectName("layout_getId")
        self.label_getId = QtWidgets.QLabel(self.widget_getBasicInfo)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_getId.setFont(font)
        self.label_getId.setObjectName("label_getId")
        self.layout_getId.addWidget(self.label_getId)
        self.LEdit_getId = QtWidgets.QLineEdit(self.widget_getBasicInfo)
        self.LEdit_getId.setObjectName("LEdit_getId")
        self.layout_getId.addWidget(self.LEdit_getId)
        self.gridLayout.addLayout(self.layout_getId, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_getBasicInfo, 0, 0, 1, 1)

        '''set get general problen ui'''
        self.widget_getGeneralProb = QtWidgets.QWidget(complain_apply_ui)
        self.widget_getGeneralProb.setObjectName("widget_getGeneralProb")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_getGeneralProb)
        self.gridLayout_2.setContentsMargins(7, 7, 7, 7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbtn_2 = QtWidgets.QRadioButton(self.widget_getGeneralProb)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_2.setFont(font)
        self.rbtn_2.setObjectName("rbtn_2")
        self.gridLayout_2.addWidget(self.rbtn_2, 0, 1, 1, 1)
        self.rbtn_3 = QtWidgets.QRadioButton(self.widget_getGeneralProb)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_3.setFont(font)
        self.rbtn_3.setObjectName("rbtn_3")
        self.gridLayout_2.addWidget(self.rbtn_3, 0, 2, 1, 1)
        self.rbtn_1 = QtWidgets.QRadioButton(self.widget_getGeneralProb)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_1.setFont(font)
        self.rbtn_1.setObjectName("rbtn_1")
        self.gridLayout_2.addWidget(self.rbtn_1, 0, 0, 1, 1)
        self.rbtn_4 = QtWidgets.QRadioButton(self.widget_getGeneralProb)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_4.setFont(font)
        self.rbtn_4.setObjectName("rbtn_4")
        self.gridLayout_2.addWidget(self.rbtn_4, 1, 0, 1, 1)
        self.rbtn_5 = QtWidgets.QRadioButton(self.widget_getGeneralProb)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_5.setFont(font)
        self.rbtn_5.setObjectName("rbtn_5")
        self.gridLayout_2.addWidget(self.rbtn_5, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_getGeneralProb, 1, 0, 1, 1)

        '''get more reasons'''
        self.widget_getMoreRsn = QtWidgets.QWidget(complain_apply_ui)
        self.widget_getMoreRsn.setObjectName("widget_getMoreRsn")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_getMoreRsn)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setObjectName("gridLayout_3")

        '''set first part of this part'''
        self.layout_getMoreRsn_L = QtWidgets.QHBoxLayout()
        self.layout_getMoreRsn_L.setObjectName("layout_getMoreRsn_L")
        self.label_getMoreRsn_L = QtWidgets.QLabel(self.widget_getMoreRsn)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_getMoreRsn_L.setFont(font)
        self.label_getMoreRsn_L.setObjectName("label_getMoreRsn_L")
        self.layout_getMoreRsn_L.addWidget(self.label_getMoreRsn_L)
        self.LEdit_getMoreRsb_L = QtWidgets.QLineEdit(self.widget_getMoreRsn)
        self.LEdit_getMoreRsb_L.setObjectName("LEdit_getMoreRsb_L")
        self.layout_getMoreRsn_L.addWidget(self.LEdit_getMoreRsb_L)
        self.gridLayout_3.addLayout(self.layout_getMoreRsn_L, 0, 0, 1, 1)

        '''set second part of this part'''
        self.layout_getMoreRsn_M = QtWidgets.QVBoxLayout()
        self.layout_getMoreRsn_M.setObjectName("layout_getMoreRsn_M")
        self.label_getMoreRsn_M = QtWidgets.QLabel(self.widget_getMoreRsn)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_getMoreRsn_M.setFont(font)
        self.label_getMoreRsn_M.setObjectName("label_getMoreRsn_M")
        self.layout_getMoreRsn_M.addWidget(self.label_getMoreRsn_M)
        self.textEdit = QtWidgets.QTextEdit(self.widget_getMoreRsn)
        self.textEdit.setObjectName("textEdit")
        self.layout_getMoreRsn_M.addWidget(self.textEdit)

        '''layout to place btns'''
        self.layout_getMoreRsnBtn = QtWidgets.QHBoxLayout()
        self.layout_getMoreRsnBtn.setObjectName("layout_getMoreRsnBtn")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_getMoreRsnBtn.addItem(spacerItem)
        self.btn_submit = QtWidgets.QPushButton(self.widget_getMoreRsn)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_submit.setFont(font)
        self.btn_submit.setObjectName("btn_submit")
        self.layout_getMoreRsnBtn.addWidget(self.btn_submit)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_getMoreRsn)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.layout_getMoreRsnBtn.addWidget(self.btn_cancel)
        self.layout_getMoreRsn_M.addLayout(self.layout_getMoreRsnBtn)

        '''layout settings'''
        self.gridLayout_3.addLayout(self.layout_getMoreRsn_M, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_getMoreRsn, 2, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 2)
        self.gridLayout_4.setRowStretch(2, 10)

        '''enhance shadow effect'''
        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_getBasicInfo.setGraphicsEffect(shadow_effect)
        self.widget_getBasicInfo.setStyleSheet("""QWidget#widget_getBasicInfo{
                                                    background-color: rgba(255,255,255,180);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_getGeneralProb.setGraphicsEffect(shadow_effect)
        self.widget_getGeneralProb.setStyleSheet("""QWidget#widget_getGeneralProb{
                                                    background-color: rgba(255,255,255,180);
                                                    border-radius: 8px}""")

        shadow_effect=QGraphicsDropShadowEffect()
        shadow_effect.setOffset(0,0)
        shadow_effect.setColor(QColor("#444444"))
        shadow_effect.setBlurRadius(5)
        self.widget_getMoreRsn.setGraphicsEffect(shadow_effect)
        self.widget_getMoreRsn.setStyleSheet("""QWidget#widget_getMoreRsn{
                                                    background-color: rgba(255,255,255,180);
                                                    border-radius: 8px}""")




        '''set line edit style'''
        with open("Qss/line_edit_style.qss") as LEditStyle:
            self.LEdit_getId.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_getMoreRsb_L.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)
            self.LEdit_getName.setStyleSheet(LEditStyle.read())
            LEditStyle.seek(0)

        '''set text edit style'''
        with open("Qss/textedit_style.qss") as TEditStyle:
            self.textEdit.setStyleSheet(TEditStyle.read())

        '''set radio btn style'''
        with open("Qss/radiobtn_style.qss") as RBtnStyle:
            self.rbtn_1.setStyleSheet(RBtnStyle.read())
            RBtnStyle.seek(0)
            self.rbtn_2.setStyleSheet(RBtnStyle.read())
            RBtnStyle.seek(0)
            self.rbtn_3.setStyleSheet(RBtnStyle.read())
            RBtnStyle.seek(0)
            self.rbtn_4.setStyleSheet(RBtnStyle.read())
            RBtnStyle.seek(0)
            self.rbtn_5.setStyleSheet(RBtnStyle.read())
            RBtnStyle.seek(0)

        '''set btn style'''
        with open("Qss/push_button_style.qss") as BtnStyle:
            self.btn_submit.setStyleSheet(BtnStyle.read())
        with open("Qss/push_button_style_lightred.qss") as BtnStyle:
            self.btn_cancel.setStyleSheet(BtnStyle.read())


        self.retranslateUi(complain_apply_ui)
        QtCore.QMetaObject.connectSlotsByName(complain_apply_ui)

        '''set connection'''
        self.btn_cancel.clicked.connect(complain_apply_ui.slot_cancel)
        self.rbtn_1.clicked.connect(self.bn1)
        self.rbtn_2.clicked.connect(self.bn2)
        self.rbtn_3.clicked.connect(self.bn3)
        self.rbtn_4.clicked.connect(self.bn4)
        self.rbtn_5.clicked.connect(self.bn5)
        self.btn_submit.clicked.connect(complain_apply_ui.submit)
        self.btn_cancel.clicked.connect(complain_apply_ui.cancel)
        self.btn_submit.clicked.connect(self.get)
        self.btn_cancel.clicked.connect(self.clear)

    def bn1(self,complain_apply_ui):
        global strreason
        strreason = self.rbtn_1.text()
        print(strreason)

    def bn3(self,complain_apply_ui):
        global strreason
        strreason = self.rbtn_2.text()

    def bn4(self,complain_apply_ui):
        global strreason
        strreason = self.rbtn_2.text()

    def bn5(self,complain_apply_ui):
        global strreason
        strreason = self.rbtn_2.text()

    def bn2(self,complain_apply_ui):
        global strreason
        strreason = self.rbtn_2.text()

    def clear(self, complain_apply_ui):
        self.LEdit_getMoreRsb_L.setText("")
        self.textEdit.setText("")
        self.LEdit_getId.setText("")
        self.LEdit_getName.setText("")

    def get(self, complain_apply_ui):
        global strreason
        strText = self.LEdit_getMoreRsb_L.text()
        specify = self.textEdit.toPlainText()
        strid = self.LEdit_getId.text()
        strname = self.LEdit_getName.text()
        print(strreason)
        print(strText)
        print(strid)
        print(strname)
        print(specify)
        info=[]
        info.append(strid)
        info.append(strname)
        info.append(strreason)
        info.append(strText)
        info.append(specify)
        info=json.dumps(info)#转为 json
        BreakDayApply.complainapply(info)
#       result=json.loads(result)
        print("接收成功，准备返回")
        return

    def retranslateUi(self, complain_apply_ui):
        _translate = QtCore.QCoreApplication.translate
        complain_apply_ui.setWindowTitle(_translate("complain_apply_ui", "Form"))
        self.label_getName.setText(_translate("complain_apply_ui", "员工姓名:"))
        self.label_getId.setText(_translate("complain_apply_ui", "员工工号:"))
        self.rbtn_2.setText(_translate("complain_apply_ui", "摄像签到失败"))
        self.rbtn_3.setText(_translate("complain_apply_ui", "摄像头损坏"))
        self.rbtn_1.setText(_translate("complain_apply_ui", "无法获取员工信息"))
        self.rbtn_4.setText(_translate("complain_apply_ui", "无法开始签到"))
        self.rbtn_5.setText(_translate("complain_apply_ui", "无法获取当日考勤信息"))
        self.label_getMoreRsn_L.setText(_translate("complain_apply_ui", "其他："))
        self.label_getMoreRsn_M.setText(_translate("complain_apply_ui", "其他理由详细描述："))
        self.btn_submit.setText(_translate("complain_apply_ui", "提交申诉"))
        self.btn_cancel.setText(_translate("complain_apply_ui", "清空"))


if __name__ == "__main__":
    app = QApplication( sys.argv )
    
    TestUi=QWidget()
    TestUi.setWindowFlags (Qt.FramelessWindowHint)
    TestUi.main_ui=Ui_Complain_Apply_Ui()
    TestUi.main_ui.setupUi(TestUi)
    TestUi.show()

    sys.exit( app.exec_() )